---
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid

staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - default
  - [abacus, 2]
  - [cargo,1]
  - [fulfillment,1]
  - [terminator,100]